// ======================================| IMPORTS |======================================
const fs = require("fs");
const path = require("path");
const http = require("http");
const pty = require("node-pty");
const crypto = require("crypto");
const express = require("express");
const { Server } = require("socket.io");
const { QueueEvents } = require("bullmq");
const stdinQueue = require("../redis/queue");
const redisConnection = require("../redis/redis-connection");
require("dotenv").config({ path: path.join(__dirname, "../.env") });

const app = express();
const server = http.createServer(app);
const io = new Server(server);
app.use(express.static(path.join(__dirname, "../frontend")));
// ==================================| IMPORTS END |======================================

const activeSessions = new Map();

// Map containing the exitCodes and messages -
const EXIT_CODE_MAP = new Map([
    [0, null], // normal exit - handled separately
    [1, ["CE", "Compilation Error"]],
    [132, ["RTE", "Runtime Error — Illegal Instruction (SIGILL)"]],
    [134, ["RTE", "Runtime Error — Aborted (SIGABRT)"]],
    [136, ["RTE", "Runtime Error — Floating Point Exception (SIGFPE)"]],
    [137, ["RTE", "Runtime Limit Exceeded (Memory or CPU Limit Hit)"]],
    [139, ["RTE", "Runtime Error — Segmentation Fault (SIGSEGV)"]],
    [152, ["TLE", "Time Limit Exceeded (CPU Time)"]],
]);

const stdinQueueEvents = new QueueEvents("stdin-jobs", {
    connection: redisConnection,
});

stdinQueueEvents.on("completed", ({ jobId, returnvalue }) => {
    io.to(returnvalue.socketID).emit("stdin-result", {
        output: returnvalue.output,
        error: returnvalue.error,
    });
});

stdinQueueEvents.on("failed", ({ jobId, failedReason }) => {
    console.log(`Job ID: ${jobId} failed: ${failedReason}`);
});

io.on("connection", (socket) => {
    console.log(`New Client Connected: ${socket.id}`);

    socket.on("stdin-run", async (data) => {
        const codeID = crypto.randomUUID();
        const pathTemp = `/tmp/${codeID}`;

        fs.mkdirSync(pathTemp, { recursive: true });
        fs.writeFileSync(`${pathTemp}/main.cpp`, data.code);
        fs.writeFileSync(`${pathTemp}/input`, data.input);

        await stdinQueue.add("job", {
            codeID,
            pathTemp,
            socketID: socket.id,
        });
    });

    socket.on("run", (data) => {
        // 1. Check if existing
        const existing = activeSessions.get(socket.id);
        if (existing) existing.cleanup();

        // 2. Remove all other socketListeners
        socket.removeAllListeners("term:in");

        // 3. Do the work here with a fresh session
        const codeID = crypto.randomUUID();

        // So the data would contain -
        // Language ID: Which would be generated by the user selected language
        // Code: The content of the text-area in the front-end
        // We give it a unique ID using crypto.randomUUID();

        const pathTemp = `/tmp/${codeID}`;
        fs.mkdirSync(`${pathTemp}`, { recursive: true });
        fs.writeFileSync(`${pathTemp}/main.cpp`, data.code);

        let ptyProcess;
        try {
            ptyProcess = pty.spawn(
                "docker",
                [
                    "run",
                    "-i",
                    "--rm",
                    "--memory",
                    "256m",
                    "--memory-swap",
                    "256m",
                    "--ulimit",
                    "cpu=5:5",
                    "-v",
                    `${pathTemp}/main.cpp:/code/main.cpp`,
                    "judge-interactive",
                    "bash",
                    "-c",
                    "g++ /code/main.cpp -o /code/main && /code/main",
                ],
                {
                    name: "xterm-color",
                    cols: 80,
                    rows: 30,
                    cwd: process.env.HOME,
                    env: process.env,
                },
            );
        } catch (error) {
            console.log(
                `Some Error Occurred while spawning the terminal in backend: ${error}`,
            );

            // Since, cleanup should only be exlusively for onExit and disconnect, we do nothing more here.
            fs.rmSync(`${pathTemp}`, { recursive: true, force: true });
        }

        if (!ptyProcess) return;

        // User inputs from the front-end are entered here.
        socket.on("term:in", (data) => {
            ptyProcess.write(data);
        });

        // The output are sent to the front-end.
        ptyProcess.onData((data) => {
            socket.emit("term:out", data);
        });

        // 4. Cleanup Session
        const cleanup = () => {
            fs.rmSync(pathTemp, { recursive: true, force: true });
            try {
                ptyProcess.kill();
            } catch (e) {
                console.log(`Error in cleanup: \n${e}`);
            }
            activeSessions.delete(socket.id);
        };

        // 5. Storing this session
        activeSessions.set(socket.id, { cleanup });

        // At normal exit - ptyProcess.onExit fires rather than socket.io disconnects
        ptyProcess.onExit(({ exitCode, signal }) => {
            if (exitCode === 0) console.log(`Normal exit: ${socket.id}`);
            else {
                const event = EXIT_CODE_MAP.get(exitCode);

                event
                    ? socket.emit(event[0], event[1])
                    : socket.emit(
                          "RTE",
                          `Runtime Error (Exit Code: ${exitCode})`,
                      );
            }

            try {
                cleanup();
            } catch (e) {} // Because cleanup also contains ptyProcess.kill() - causing error here;
        });
    });

    // Abrupt disconnection would lead to fire socket.on('disconnect')
    socket.on("disconnect", (reason) => {
        console.log(`Client disconnected: ${socket.id} — reason: ${reason}`);

        const existing = activeSessions.get(socket.id);
        if (existing) existing.cleanup();
    });
});

server.listen(process.env.PORT, () => {
    console.log("Server listening at port: http://localhost:9001");
});
