/*  worker.js -

#.  What I did here -
1.  Creation of a pool of docker of size, 2 -> At the time of server startup
2.  Pull a Job from Queue -> job.data = { codeID, pathTemp, socketID }
    codeID -> generated by randomUUID(), pathTemp -> { code, input }'s location on the Host, socketID -> User's ID
3.  Accquire a container to perform the job -> From the pool
4.  Send the { containerID, pathTemp } to executionStdin.js -> To compile the code and provide the output
5.  Return the { output, error, socketID } as the final results.
6.  Release the container, Remove the pathTemp FROM: HOST

#   Notes -
1.  All this with the concurrency of 4 -> 4 Jobs can be pulled and executed at once
2.  Graceful shutdown implemented
*/

const fs = require("fs");
const { Worker } = require("bullmq");
const logger = require("../backend/utils/logger");
const redisConnection = require("./redis-connection");

const pool = require("../backend/execution/containerPool");
const execute = require("../backend/execution/executionStdin");

(async () => {
    await pool.init();
    logger.info("Worker pool initialized");
})();

const gracefulShutdown = async () => {
    logger.info("Worker graceful shutdown initiated");
    await worker.close();
    await pool.destroyAll();
    await redisConnection.quit();
    logger.info("Worker shutdown complete");
    process.exit(0);
};

const handleStdinJobs = async (job) => {
    const { codeID, pathTemp, socketID } = job.data;
    const container = await pool.acquire();

    try {
        const { stdout, stderr } = await execute(container.id, pathTemp);
        logger.info("Job completed", { codeID });

        return {
            output: stdout,
            error: stderr,
        };
    } catch (err) {
        logger.error("Job execution failed", {
            error: err.message,
            codeID,
        });

        return {
            output: err.stdout || "",
            error: err.stderr || err.message,
        };
    } finally {
        await pool.release(container);
        fs.rmSync(pathTemp, { recursive: true, force: true });
        logger.info("Job cleanup complete", { pathTemp, socketID });
    }
};

const worker = new Worker("stdin-jobs", handleStdinJobs, {
    connection: redisConnection,
    concurrency: parseInt(process.env.WORKER_CONCURRENCY) || 4,
});

process.on("SIGTERM", gracefulShutdown);
process.on("SIGINT", gracefulShutdown);

module.exports = worker;
